//  users
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_UNREAD_MESSAGE_COUNT = 'SET_UNREAD_MESSAGE_COUNT';
export const SET_BALANCE = 'SET_BALANCE';

// admin
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOADED = 'ADMIN_LOADED';

//  messages
export const MSG_SUCCESS = 'success';
export const MSG_ERROR = 'error';
export const MSG_INFO = 'info';
export const MSG_WARNING = 'warning';
export const MSG_OPEN = 'MSG_OPEN';
export const MSG_CLOSE = 'MSG_CLOSE';

//url
export const SET_URL = 'SET_URL';

//action customer
export const CUSTOMER_QUERY = 'CUSTOMER_QUERY';
export const PAGINATION_FOR_CUSTOMER = 'PAGINATION_FOR_CUSTOMER';
export const LOADING_CUSTOMER_TABLE = 'LOADING_CUSTOMER_TABLE';
export const ADD_MAIN_INFO = 'ADD_MAIN_INFO';

//action question
export const QUESTION_QUERY = 'QUESTION_QUERY';
export const PAGINATION_FOR_QUESTION = 'PAGINATION_FOR_QUESTION';
export const LOADING_QUESTION_TABLE = 'LOADING_QUESTION_TABLE';
export const QUESTION_QUERY_ONE = 'QUESTION_QUERY_ONE';
export const SET_CURRENT_QUESTION_INFO = 'SET_CURRENT_QUESTION_INFO';
export const BRAIN_GAME_TYPE_QUERY = 'BRAIN_GAME_TYPE_QUERY';
export const SET_SCORE = 'SET_SCORE';

// action mygames
export const MY_GAMES_LOADED = 'MY_GAMES_LOADED';
export const MY_HISTORY_LOADED = 'MY_HISTORY_LOADED';
export const SET_CHAT_ROOM_INFO = 'SET_CHAT_ROOM_INFO';

// action item
export const ITEM_QUERY_ONE = 'ITEM_QUERY_ONE';
export const ITEM_QUERY = 'ITEM-QUERY';
//PAGINATION
export const PAGINATION_FOR_ITEM = 'PAGINATION_FOR_ITEM';
export const LOADING_ITEM_TABLE = 'LOADING_ITEM_TABLE';
export const ADD_TOTAL = 'ADD_TOTAL';
export const SET_CURRENT_PRODUCT_INFO = 'SET_CURRENT_PRODUCT_INFO';
export const SET_CURRENT_PRODUCT_ID = 'SET_CURRENT_PRODUCT_ID';

//action landing
export const LANDING_QUERY = 'LANDING_QUERY';
export const LANDING_QUERY_ONE = 'LANDING_QUERY_ONE';
export const LOADING_LANDING_TABLE = 'LOADING_LANDING_TABLE';
export const PAGINATION_FOR_LANDING = 'PAGINATION_FOR_LANDING';
export const ADD_LANDING_TOTAL = 'ADD_LANDING_TOTAL';

//logic
export const SET_SOCKET = 'SET_SOCKET';
export const GAMETYPE_LOADED = 'GAMETYPE_LOADED';
export const ROOMINFO_LOADED = 'ROOMINFO_LOADED';
export const ROOMS_LOADED = 'ROOMS_LOADED';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const SET_CUR_ROOM_INFO = 'SET_CUR_ROOM_INFO';
export const BET_SUCCESS = 'BET_SUCCESS';
export const BET_FAIL = 'BET_FAIL';

export const MSG_CREATE_ROOM_FAIL = 'MSG_CREATE_ROOM_FAIL';
export const MSG_CREATE_ROOM_SUCCESS = 'MSG_CREATE_ROOM_SUCCESS';
export const MSG_ROOMS_LOAD_FAILED = 'MSG_ROOMS_LOAD_FAILED';
export const MSG_GAMETYPE_LOAD_FAILED = 'MSG_GAMETYPE_LOAD_FAILED';